---
- name: "Install yum package of influxdb from rpm"
  yum:
    name: "{{rpm_influxdb}}"

- name: "Start influxdb"
  service:
    name: influxdb
    state: started
    enabled: yes

- name: "Wait 300 seconds for port 8086 to become open on the host, don't start checking for 10 seconds"
  wait_for:
    port: 8086
    delay: 10

- name: setup dabatase on influxdb
  shell: "curl -X POST 'http://localhost:8086/db?u={{ metrics_db_user }}&p={{ metrics_db_password }}' -d '{\"name\": \"{{ metrics_db_name }}\"}'"
  
- name: "Restart influxdb"
  service:
    name: influxdb
    state: restarted
    enabled: yes